# Site settings
title: "Dr.Hossein Sadr"
description: "Ph.D of Computer"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Hossein Sadr"
resume_title:                   "About Me"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "sadr@qiau.ac.ir"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "phone"
resume_contact_address:         "Address"

resume_header_contact_info:     "Address • sadr@qiau.ac.ir"
display_header_contact_info:    "false"

resume_header_intro: "<p> My research interests include natural language processing, data mining, and machine learning and deep learning. In particular, I am interested in employing deep learning in different applications of natural language processing especially sentiment analysis. The field of opinion mining, or sentiment analysis, has become active in recent years. Since different kinds of deep neural networks differ in their structures, they are probably extracting different features. Investigating whether features generated by heterogeneous deep neural networks can be combined by multi-view learning to improve the overall performance is a follow-up research work. I am also interested in the following topics: </p><h4>Deep Learning:</h4><ul class='resume-item-list'><li>Sequence to Sequence Models</li><li>Convolutional Neural Network</li><li>Recursive Neural Network</li><li>Recurrent Neural Network</li><li>Generative Adversarial Network</li><li>Semantic Word Embedding</li><li>Multi-task Transfer Learning</li><li>Reinforcement Learning</li></ul><h4>Information Retrieval:</h4><ul class='resume-item-list'><li>Web Document Ranking</li><li>Query Reformulation</li><li>Understanding User's Query Intent</li><li>Clustering/Classification</li></ul><h4>Natural Language Engineering:</h4><ul class='resume-item-list'><li>Sentiment Analysis</li><li>Machine translation/Transliteration</li><li>Semantic Relatedness</li><li>Topic Modeling</li></ul>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/hosseinsadr/"
  resume_twitter_url:           "https://twitter.com/Sadr_ir"
  resume_linkedin_url:          "https://www.linkedin.com/in/hossein-sadr-1b964a49/"
  resume_instagram_url:         "https://www.instagram.com/hosseinsadr_/"
  resume_website_url:           "https://scholar.google.com/citations?user=ohcVchoAAAAJ&hl=en"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
